[package]
name = "kekeke"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.56", features = ["derive"] }
csv = "1.4.0"
rust_decimal = "1.40.0"
rust_decimal_macros = "1.33"
serde = { version = "1.0.228", features = ["derive"] }
